### ISSUE TITLE
Picotts

### ISSUE THREAD

**Issue by deennoo** [maditnerd/yana-linux#9]
Bonjour.

Depuis que google a mis une securité pour ne plus autoriser les demandes de boot le client ne fonctionne plus. C'est bien dommage.

Une solution serait d'utiliser picotts : 

http://www.supinfo.com/articles/single/1587-synthese-vocale-fluide-linux-avec-pico

Cloud free, "facile" a utiliser.

J'imagine que les changements sont a faire dans le script tts.sh 

Tu confirmes ?

**Comment by remisarrailh** [comment]
C'est effectivement dans tts.sh que ça se passe.

Mais je te conseillerais de te pencher sur jarvis : http://domotiquefacile.fr/jarvis/ qui utilise plusieurs moteur de reconnaissance vocale au choix. (snowball/pocket sphynx/bing)

Dont celui-ci : https://snowboy.kitt.ai/ qui permet de faire de la reconnaissance vocale avec des mots clés hors ligne.

Je suis en train de tester c'est vraiment bien fichu et c'est relativement facile d'ajouter des nouvelles commandes.
